"""create core metasignal tables

Revision ID: 61738c5dba04
Revises: 
Create Date: 2026-05-05 01:26:39.716320
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '61738c5dba04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('numerator_sql', sa.Text(), nullable=False),
    sa.Column('denominator_sql', sa.Text(), nullable=False),
    sa.Column('denominator_type', sa.String(length=64), nullable=False),
    sa.Column('filter_sql', sa.Text(), nullable=True),
    sa.Column('grain', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=32), nullable=False),
    sa.Column('is_guardrail', sa.Boolean(), nullable=False),
    sa.Column('guardrail_tolerance_pct', sa.Float(), nullable=True),
    sa.Column('guardrail_window_days', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('config_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['metric_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_run_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=True),
    sa.Column('rows_expected', sa.Integer(), nullable=True),
    sa.Column('quality_checks_passed', sa.Integer(), nullable=True),
    sa.Column('quality_checks_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config_hash', sa.String(length=128), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('scenario_name', sa.String(length=256), nullable=False),
    sa.Column('scenario_type', sa.String(length=128), nullable=False),
    sa.Column('simulation_day', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('injected', sa.Boolean(), nullable=False),
    sa.Column('injection_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_system_behavior', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id')
    )
    op.create_table('data_quality_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('check_name', sa.String(length=128), nullable=False),
    sa.Column('entity', sa.String(length=128), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('check_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('primary_metric_id', sa.UUID(), nullable=True),
    sa.Column('guardrail_metric_configs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_mde', sa.Float(), nullable=True),
    sa.Column('expected_duration_days', sa.Integer(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('use_cuped', sa.Boolean(), nullable=False),
    sa.Column('assignment_method', sa.String(length=64), nullable=False),
    sa.Column('treatment_split_pct', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_metric_id'], ['metric_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_key')
    )
    op.create_table('metric_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('metric_version', sa.Integer(), nullable=False),
    sa.Column('computation_date', sa.Date(), nullable=False),
    sa.Column('grain_period', sa.String(length=64), nullable=False),
    sa.Column('numerator_value', sa.Float(), nullable=True),
    sa.Column('denominator_value', sa.Float(), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('segment_key', sa.String(length=256), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('quality_passed', sa.Boolean(), nullable=False),
    sa.Column('late_arrival_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run_log.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_id', 'metric_version', 'grain_period', 'segment_key', name='uq_metric_result_grain_segment')
    )
    op.create_table('experiment_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evaluation_day', sa.Integer(), nullable=True),
    sa.Column('sample_size_treatment', sa.Integer(), nullable=False),
    sa.Column('sample_size_control', sa.Integer(), nullable=False),
    sa.Column('primary_metric_lift', sa.Float(), nullable=True),
    sa.Column('primary_metric_ci_lower', sa.Float(), nullable=True),
    sa.Column('primary_metric_ci_upper', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('is_significant', sa.Boolean(), nullable=True),
    sa.Column('cuped_applied', sa.Boolean(), nullable=False),
    sa.Column('cuped_theta', sa.Float(), nullable=True),
    sa.Column('variance_reduction_pct', sa.Float(), nullable=True),
    sa.Column('cuped_edge_case', sa.String(length=64), nullable=True),
    sa.Column('cuped_fallback', sa.String(length=64), nullable=True),
    sa.Column('guardrail_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('guardrails_cleared', sa.Boolean(), nullable=True),
    sa.Column('peeking_warning', sa.Boolean(), nullable=False),
    sa.Column('simpsons_flag', sa.Boolean(), nullable=False),
    sa.Column('segment_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('novelty_flag', sa.Boolean(), nullable=False),
    sa.Column('decision_recommendation', sa.String(length=64), nullable=False),
    sa.Column('recommendation_reason', sa.Text(), nullable=False),
    sa.Column('evaluator_version', sa.String(length=64), nullable=False),
    sa.Column('is_aa_test', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=True),
    sa.Column('system_recommendation', sa.String(length=64), nullable=False),
    sa.Column('final_decision', sa.String(length=64), nullable=False),
    sa.Column('reviewer_name', sa.String(length=128), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['experiment_evaluations.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision_log')
    op.drop_table('experiment_evaluations')
    op.drop_table('metric_results')
    op.drop_table('experiments')
    op.drop_table('data_quality_checks')
    op.drop_table('simulation_events')
    op.drop_table('pipeline_run_log')
    op.drop_table('metric_definitions')
    # ### end Alembic commands ###
